# Generated by Django 3.0.2 on 2020-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimental_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monkey', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('fixation_time_min', models.IntegerField(blank=True, null=True)),
                ('fixation_time_max', models.IntegerField(blank=True, null=True)),
                ('initial_stock', models.IntegerField(blank=True, null=True)),
                ('inter_trial_time_min', models.IntegerField(blank=True, null=True)),
                ('inter_trial_time_max', models.IntegerField(blank=True, null=True)),
                ('max_decision_time', models.IntegerField(blank=True, null=True)),
                ('max_return_time', models.IntegerField(blank=True, null=True)),
                ('punishment_time', models.IntegerField(blank=True, null=True)),
                ('result_display_time', models.IntegerField(blank=True, null=True)),
                ('reward_time', models.IntegerField(blank=True, null=True)),
                ('valve_opening_time', models.IntegerField(blank=True, null=True)),
                ('control_proportion', models.IntegerField(blank=True, null=True)),
                ('incongruent_proportion', models.IntegerField(blank=True, null=True)),
                ('with_losses_proportion', models.IntegerField(blank=True, null=True)),
                ('choice', models.IntegerField(blank=True, null=True)),
                ('dice_output', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('fixation_time', models.IntegerField(blank=True, null=True)),
                ('inter_trial_time', models.IntegerField(blank=True, null=True)),
                ('left_beginning_angle', models.IntegerField(blank=True, null=True)),
                ('left_p', models.IntegerField(blank=True, null=True)),
                ('left_x0', models.IntegerField(blank=True, null=True)),
                ('right_beginning_angle', models.IntegerField(blank=True, null=True)),
                ('right_p', models.IntegerField(blank=True, null=True)),
                ('right_x0', models.IntegerField(blank=True, null=True)),
                ('time_to_come_back_to_the_grip', models.IntegerField(blank=True, null=True)),
                ('time_to_decide', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
