# Generated by Django 3.0.2 on 2020-02-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimental_data', '0002_experimentaldata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentaldata',
            options={'managed': False},
        ),
    ]
