# Generated by Django 3.0.2 on 2020-02-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimental_data', '0003_auto_20200203_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentaldata',
            options={},
        ),
    ]
