# Generated by Django 3.0.2 on 2020-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimental_data', '0004_auto_20200203_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentaldata',
            name='left_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentaldata',
            name='right_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='experimentaldata',
            table='experimental_data',
        ),
    ]
